/**
 * Base de codes CIM-10 courants en ORL
 * Organisés par catégorie anatomique
 */

import type { CIM10Code } from '@/types/codage';

export const CIM10_ORL_CODES: CIM10Code[] = [
  // ============================================================================
  // OREILLE (H60-H95)
  // ============================================================================

  // Otites externes
  {
    code: 'H60.0',
    libelle: "Abcès de l'oreille externe",
    libelle_court: 'Abcès oreille ext.',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H60.3',
    libelle: 'Otite externe infectieuse',
    libelle_court: 'Otite ext. infect.',
    categorie: 'Oreille',
    frequence: 85,
  },
  {
    code: 'H60.5',
    libelle: 'Otite externe aiguë, non infectieuse',
    libelle_court: 'Otite ext. non infect.',
    categorie: 'Oreille',
    frequence: 40,
  },
  {
    code: 'H60.9',
    libelle: 'Otite externe, sans précision',
    libelle_court: 'Otite externe SAI',
    categorie: 'Oreille',
    frequence: 90,
  },
  {
    code: 'H61.0',
    libelle: "Périchondrite de l'oreille externe",
    libelle_court: 'Périchondrite',
    categorie: 'Oreille',
    frequence: 20,
  },
  {
    code: 'H61.2',
    libelle: 'Bouchon de cérumen',
    libelle_court: 'Bouchon cérumen',
    categorie: 'Oreille',
    frequence: 95,
  },

  // Otites moyennes
  {
    code: 'H65.0',
    libelle: 'Otite moyenne aiguë séreuse',
    libelle_court: 'OMA séreuse',
    categorie: 'Oreille',
    frequence: 75,
  },
  {
    code: 'H65.1',
    libelle: 'Otite moyenne aiguë et subaiguë',
    libelle_court: 'OMA subaiguë',
    categorie: 'Oreille',
    frequence: 60,
  },
  {
    code: 'H65.2',
    libelle: 'Otite moyenne séreuse chronique',
    libelle_court: 'OSM chronique',
    categorie: 'Oreille',
    frequence: 80,
  },
  {
    code: 'H65.3',
    libelle: 'Otite moyenne muqueuse chronique',
    libelle_court: 'OM muqueuse chron.',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.4',
    libelle: 'Autres otites moyennes chroniques non suppurées',
    libelle_court: 'OM chron. non supp.',
    categorie: 'Oreille',
    frequence: 40,
  },
  {
    code: 'H65.9',
    libelle: 'Otite moyenne non suppurée, sans précision',
    libelle_court: 'OM non supp. SAI',
    categorie: 'Oreille',
    frequence: 70,
  },
  {
    code: 'H66.0',
    libelle: 'Otite moyenne suppurée aiguë',
    libelle_court: 'OMA suppurée',
    categorie: 'Oreille',
    frequence: 85,
  },
  {
    code: 'H66.1',
    libelle: 'Otite moyenne suppurée chronique tubotympanique',
    libelle_court: 'OM chron. tubotymp.',
    categorie: 'Oreille',
    frequence: 55,
  },
  {
    code: 'H66.2',
    libelle: 'Otite moyenne suppurée chronique attico-antrale',
    libelle_court: 'OM chron. attico-antr.',
    categorie: 'Oreille',
    frequence: 35,
  },
  {
    code: 'H66.3',
    libelle: 'Autres otites moyennes suppurées chroniques',
    libelle_court: 'OM supp. chron. autre',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H66.4',
    libelle: 'Otite moyenne suppurée, sans précision',
    libelle_court: 'OM suppurée SAI',
    categorie: 'Oreille',
    frequence: 75,
  },
  {
    code: 'H66.9',
    libelle: 'Otite moyenne, sans précision',
    libelle_court: 'Otite moyenne SAI',
    categorie: 'Oreille',
    frequence: 90,
  },
  {
    code: 'H67.0',
    libelle: 'Otite moyenne au cours de maladies bactériennes',
    libelle_court: 'OM bactérienne',
    categorie: 'Oreille',
    frequence: 25,
  },

  // Pathologie tympanique
  {
    code: 'H72.0',
    libelle: 'Perforation centrale du tympan',
    libelle_court: 'Perf. tympan centr.',
    categorie: 'Oreille',
    frequence: 65,
  },
  {
    code: 'H72.1',
    libelle: 'Perforation atticale du tympan',
    libelle_court: 'Perf. tympan attic.',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H72.2',
    libelle: 'Autres perforations marginales du tympan',
    libelle_court: 'Perf. tympan marg.',
    categorie: 'Oreille',
    frequence: 25,
  },
  {
    code: 'H72.9',
    libelle: 'Perforation du tympan, sans précision',
    libelle_court: 'Perf. tympan SAI',
    categorie: 'Oreille',
    frequence: 70,
  },
  {
    code: 'H73.0',
    libelle: 'Myringite aiguë',
    libelle_court: 'Myringite aiguë',
    categorie: 'Oreille',
    frequence: 45,
  },
  {
    code: 'H73.1',
    libelle: 'Myringite chronique',
    libelle_court: 'Myringite chronique',
    categorie: 'Oreille',
    frequence: 20,
  },
  {
    code: 'H74.0',
    libelle: 'Tympanosclérose',
    libelle_court: 'Tympanosclérose',
    categorie: 'Oreille',
    frequence: 40,
  },
  {
    code: 'H74.1',
    libelle: "Otite adhésive de l'oreille moyenne",
    libelle_court: 'Otite adhésive',
    categorie: 'Oreille',
    frequence: 25,
  },

  // Mastoïdite et cholestéatome
  {
    code: 'H70.0',
    libelle: 'Mastoïdite aiguë',
    libelle_court: 'Mastoïdite aiguë',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H70.1',
    libelle: 'Mastoïdite chronique',
    libelle_court: 'Mastoïdite chronique',
    categorie: 'Oreille',
    frequence: 25,
  },
  {
    code: 'H71',
    libelle: "Cholestéatome de l'oreille moyenne",
    libelle_court: 'Cholestéatome',
    categorie: 'Oreille',
    frequence: 45,
  },

  // Otospongiose
  {
    code: 'H80.0',
    libelle: 'Otospongiose de la fenêtre ovale, non oblitérante',
    libelle_court: 'Otospong. non oblitér.',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H80.1',
    libelle: 'Otospongiose de la fenêtre ovale, oblitérante',
    libelle_court: 'Otospong. oblitérante',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H80.2',
    libelle: 'Otospongiose cochléaire',
    libelle_court: 'Otospong. cochléaire',
    categorie: 'Oreille',
    frequence: 25,
  },
  {
    code: 'H80.9',
    libelle: 'Otospongiose, sans précision',
    libelle_court: 'Otospongiose SAI',
    categorie: 'Oreille',
    frequence: 55,
  },

  // Vertiges et troubles vestibulaires
  {
    code: 'H81.0',
    libelle: 'Maladie de Ménière',
    libelle_court: 'Ménière',
    categorie: 'Oreille',
    frequence: 65,
  },
  {
    code: 'H81.1',
    libelle: 'Vertige paroxystique bénin',
    libelle_court: 'VPPB',
    categorie: 'Oreille',
    frequence: 90,
  },
  {
    code: 'H81.2',
    libelle: 'Névrite vestibulaire',
    libelle_court: 'Névrite vestibulaire',
    categorie: 'Oreille',
    frequence: 55,
  },
  {
    code: 'H81.3',
    libelle: 'Autres vertiges périphériques',
    libelle_court: 'Vertiges périph.',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81.4',
    libelle: "Vertige d'origine centrale",
    libelle_court: 'Vertige central',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H81.9',
    libelle: 'Troubles de la fonction vestibulaire, sans précision',
    libelle_court: 'Trouble vestib. SAI',
    categorie: 'Oreille',
    frequence: 60,
  },
  {
    code: 'H82',
    libelle: 'Syndromes vertigineux au cours de maladies classées ailleurs',
    libelle_court: 'Vertiges secondaires',
    categorie: 'Oreille',
    frequence: 20,
  },
  {
    code: 'H83.0',
    libelle: 'Labyrinthite',
    libelle_court: 'Labyrinthite',
    categorie: 'Oreille',
    frequence: 40,
  },
  {
    code: 'H83.2',
    libelle: 'Dysfonctionnement labyrinthique',
    libelle_court: 'Dysfct labyrinthique',
    categorie: 'Oreille',
    frequence: 35,
  },
  {
    code: 'H83.3',
    libelle: "Effets du bruit sur l'oreille interne",
    libelle_court: 'Trauma sonore',
    categorie: 'Oreille',
    frequence: 50,
  },

  // Surdité
  {
    code: 'H90.0',
    libelle: 'Surdité de transmission bilatérale',
    libelle_court: 'Surdité transm. bilat.',
    categorie: 'Oreille',
    frequence: 55,
  },
  {
    code: 'H90.1',
    libelle: 'Surdité de transmission unilatérale avec audition normale controlatérale',
    libelle_court: 'Surdité transm. unilat.',
    categorie: 'Oreille',
    frequence: 45,
  },
  {
    code: 'H90.2',
    libelle: 'Surdité de transmission, sans précision',
    libelle_court: 'Surdité transm. SAI',
    categorie: 'Oreille',
    frequence: 60,
  },
  {
    code: 'H90.3',
    libelle: 'Surdité de perception bilatérale',
    libelle_court: 'Surdité perc. bilat.',
    categorie: 'Oreille',
    frequence: 85,
  },
  {
    code: 'H90.4',
    libelle: 'Surdité de perception unilatérale avec audition normale controlatérale',
    libelle_court: 'Surdité perc. unilat.',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.5',
    libelle: 'Surdité de perception, sans précision',
    libelle_court: 'Surdité perc. SAI',
    categorie: 'Oreille',
    frequence: 75,
  },
  {
    code: 'H90.6',
    libelle: 'Surdité mixte bilatérale',
    libelle_court: 'Surdité mixte bilat.',
    categorie: 'Oreille',
    frequence: 45,
  },
  {
    code: 'H90.7',
    libelle: 'Surdité mixte unilatérale',
    libelle_court: 'Surdité mixte unilat.',
    categorie: 'Oreille',
    frequence: 30,
  },
  {
    code: 'H90.8',
    libelle: 'Surdité mixte, sans précision',
    libelle_court: 'Surdité mixte SAI',
    categorie: 'Oreille',
    frequence: 40,
  },
  {
    code: 'H91.0',
    libelle: "Perte d'audition ototoxique",
    libelle_court: 'Surdité ototoxique',
    categorie: 'Oreille',
    frequence: 25,
  },
  {
    code: 'H91.1',
    libelle: 'Presbyacousie',
    libelle_court: 'Presbyacousie',
    categorie: 'Oreille',
    frequence: 90,
  },
  {
    code: 'H91.2',
    libelle: "Perte d'audition brusque idiopathique",
    libelle_court: 'Surdité brusque',
    categorie: 'Oreille',
    frequence: 60,
  },
  {
    code: 'H91.9',
    libelle: "Perte d'audition, sans précision",
    libelle_court: 'Hypoacousie SAI',
    categorie: 'Oreille',
    frequence: 70,
  },

  // Acouphènes et autres
  {
    code: 'H93.0',
    libelle: "Troubles dégénératifs et vasculaires de l'oreille",
    libelle_court: 'Troubles vasc. oreille',
    categorie: 'Oreille',
    frequence: 25,
  },
  {
    code: 'H93.1',
    libelle: 'Acouphènes',
    libelle_court: 'Acouphènes',
    categorie: 'Oreille',
    frequence: 90,
  },
  {
    code: 'H93.2',
    libelle: 'Autres perceptions auditives anormales',
    libelle_court: 'Percept. audit. anorm.',
    categorie: 'Oreille',
    frequence: 20,
  },
  {
    code: 'H93.3',
    libelle: 'Troubles du nerf auditif',
    libelle_court: 'Trouble nerf VIII',
    categorie: 'Oreille',
    frequence: 30,
  },

  // ============================================================================
  // NEZ ET SINUS (J00-J39, R04)
  // ============================================================================

  // Rhinites et rhinopharyngites
  {
    code: 'J00',
    libelle: 'Rhinopharyngite aiguë [rhume banal]',
    libelle_court: 'Rhume',
    categorie: 'Nez',
    frequence: 95,
  },
  {
    code: 'J30.0',
    libelle: 'Rhinite vasomotrice',
    libelle_court: 'Rhinite vasomotrice',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.1',
    libelle: 'Rhinite allergique due au pollen',
    libelle_court: 'Rhinite pollen',
    categorie: 'Nez',
    frequence: 85,
  },
  {
    code: 'J30.2',
    libelle: 'Autres rhinites allergiques saisonnières',
    libelle_court: 'Rhinite saisonn.',
    categorie: 'Nez',
    frequence: 55,
  },
  {
    code: 'J30.3',
    libelle: 'Autres rhinites allergiques',
    libelle_court: 'Rhinite allerg. autre',
    categorie: 'Nez',
    frequence: 60,
  },
  {
    code: 'J30.4',
    libelle: 'Rhinite allergique, sans précision',
    libelle_court: 'Rhinite allerg. SAI',
    categorie: 'Nez',
    frequence: 80,
  },
  {
    code: 'J31.0',
    libelle: 'Rhinite chronique',
    libelle_court: 'Rhinite chronique',
    categorie: 'Nez',
    frequence: 70,
  },
  {
    code: 'J31.1',
    libelle: 'Rhinopharyngite chronique',
    libelle_court: 'Rhinopharyngite chron.',
    categorie: 'Nez',
    frequence: 45,
  },
  {
    code: 'J31.2',
    libelle: 'Pharyngite chronique',
    libelle_court: 'Pharyngite chronique',
    categorie: 'Nez',
    frequence: 50,
  },

  // Sinusites
  {
    code: 'J01.0',
    libelle: 'Sinusite maxillaire aiguë',
    libelle_court: 'Sinusite max. aiguë',
    categorie: 'Nez',
    frequence: 90,
  },
  {
    code: 'J01.1',
    libelle: 'Sinusite frontale aiguë',
    libelle_court: 'Sinusite front. aiguë',
    categorie: 'Nez',
    frequence: 55,
  },
  {
    code: 'J01.2',
    libelle: 'Sinusite ethmoïdale aiguë',
    libelle_court: 'Sinusite ethm. aiguë',
    categorie: 'Nez',
    frequence: 40,
  },
  {
    code: 'J01.3',
    libelle: 'Sinusite sphénoïdale aiguë',
    libelle_court: 'Sinusite sphén. aiguë',
    categorie: 'Nez',
    frequence: 25,
  },
  {
    code: 'J01.4',
    libelle: 'Pansinusite aiguë',
    libelle_court: 'Pansinusite aiguë',
    categorie: 'Nez',
    frequence: 35,
  },
  {
    code: 'J01.9',
    libelle: 'Sinusite aiguë, sans précision',
    libelle_court: 'Sinusite aiguë SAI',
    categorie: 'Nez',
    frequence: 85,
  },
  {
    code: 'J32.0',
    libelle: 'Sinusite maxillaire chronique',
    libelle_court: 'Sinusite max. chron.',
    categorie: 'Nez',
    frequence: 75,
  },
  {
    code: 'J32.1',
    libelle: 'Sinusite frontale chronique',
    libelle_court: 'Sinusite front. chron.',
    categorie: 'Nez',
    frequence: 40,
  },
  {
    code: 'J32.2',
    libelle: 'Sinusite ethmoïdale chronique',
    libelle_court: 'Sinusite ethm. chron.',
    categorie: 'Nez',
    frequence: 45,
  },
  {
    code: 'J32.3',
    libelle: 'Sinusite sphénoïdale chronique',
    libelle_court: 'Sinusite sphén. chron.',
    categorie: 'Nez',
    frequence: 20,
  },
  {
    code: 'J32.4',
    libelle: 'Pansinusite chronique',
    libelle_court: 'Pansinusite chron.',
    categorie: 'Nez',
    frequence: 30,
  },
  {
    code: 'J32.9',
    libelle: 'Sinusite chronique, sans précision',
    libelle_court: 'Sinusite chron. SAI',
    categorie: 'Nez',
    frequence: 70,
  },

  // Polypes et déviations
  {
    code: 'J33.0',
    libelle: 'Polype des fosses nasales',
    libelle_court: 'Polype nasal',
    categorie: 'Nez',
    frequence: 65,
  },
  {
    code: 'J33.1',
    libelle: 'Dégénérescence polypoïde du sinus',
    libelle_court: 'Polypose sinusienne',
    categorie: 'Nez',
    frequence: 55,
  },
  {
    code: 'J33.8',
    libelle: 'Autres polypes des sinus',
    libelle_court: 'Polype sinus autre',
    categorie: 'Nez',
    frequence: 30,
  },
  {
    code: 'J33.9',
    libelle: 'Polype nasal, sans précision',
    libelle_court: 'Polype nasal SAI',
    categorie: 'Nez',
    frequence: 60,
  },
  {
    code: 'J34.0',
    libelle: 'Abcès, furoncle et anthrax du nez',
    libelle_court: 'Abcès nez',
    categorie: 'Nez',
    frequence: 25,
  },
  {
    code: 'J34.1',
    libelle: 'Kyste ou mucocèle du nez et du sinus',
    libelle_court: 'Kyste sinus',
    categorie: 'Nez',
    frequence: 35,
  },
  {
    code: 'J34.2',
    libelle: 'Déviation de la cloison nasale',
    libelle_court: 'Déviation cloison',
    categorie: 'Nez',
    frequence: 80,
  },
  {
    code: 'J34.3',
    libelle: 'Hypertrophie des cornets',
    libelle_court: 'Hypertrophie cornets',
    categorie: 'Nez',
    frequence: 70,
  },
  {
    code: 'J34.8',
    libelle: 'Autres troubles du nez et des sinus',
    libelle_court: 'Trouble nez autre',
    categorie: 'Nez',
    frequence: 40,
  },

  // Épistaxis
  {
    code: 'R04.0',
    libelle: 'Épistaxis',
    libelle_court: 'Épistaxis',
    categorie: 'Nez',
    frequence: 85,
  },

  // ============================================================================
  // GORGE ET PHARYNX (J02-J06, J35-J39, R49)
  // ============================================================================

  // Pharyngites et angines
  {
    code: 'J02.0',
    libelle: 'Pharyngite streptococcique',
    libelle_court: 'Angine strepto',
    categorie: 'Gorge',
    frequence: 75,
  },
  {
    code: 'J02.8',
    libelle: "Pharyngite aiguë due à d'autres micro-organismes",
    libelle_court: 'Pharyngite autre',
    categorie: 'Gorge',
    frequence: 45,
  },
  {
    code: 'J02.9',
    libelle: 'Pharyngite aiguë, sans précision',
    libelle_court: 'Pharyngite aiguë SAI',
    categorie: 'Gorge',
    frequence: 85,
  },
  {
    code: 'J03.0',
    libelle: 'Amygdalite streptococcique',
    libelle_court: 'Amygdalite strepto',
    categorie: 'Gorge',
    frequence: 70,
  },
  {
    code: 'J03.8',
    libelle: "Amygdalite aiguë due à d'autres micro-organismes",
    libelle_court: 'Amygdalite autre',
    categorie: 'Gorge',
    frequence: 40,
  },
  {
    code: 'J03.9',
    libelle: 'Amygdalite aiguë, sans précision',
    libelle_court: 'Amygdalite aiguë SAI',
    categorie: 'Gorge',
    frequence: 80,
  },
  {
    code: 'J04.0',
    libelle: 'Laryngite aiguë',
    libelle_court: 'Laryngite aiguë',
    categorie: 'Gorge',
    frequence: 75,
  },
  {
    code: 'J04.1',
    libelle: 'Trachéite aiguë',
    libelle_court: 'Trachéite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J04.2',
    libelle: 'Laryngo-trachéite aiguë',
    libelle_court: 'Laryngo-trachéite',
    categorie: 'Gorge',
    frequence: 55,
  },
  {
    code: 'J05.0',
    libelle: 'Laryngite obstructive aiguë [croup]',
    libelle_court: 'Croup',
    categorie: 'Gorge',
    frequence: 35,
  },
  {
    code: 'J05.1',
    libelle: 'Épiglottite aiguë',
    libelle_court: 'Épiglottite',
    categorie: 'Gorge',
    frequence: 25,
  },
  {
    code: 'J06.0',
    libelle: 'Laryngopharyngite aiguë',
    libelle_court: 'Laryngopharyngite',
    categorie: 'Gorge',
    frequence: 45,
  },
  {
    code: 'J06.9',
    libelle: 'Infection aiguë des voies respiratoires supérieures, sans précision',
    libelle_court: 'IVRS aiguë SAI',
    categorie: 'Gorge',
    frequence: 90,
  },

  // Amygdales et végétations
  {
    code: 'J35.0',
    libelle: 'Amygdalite chronique',
    libelle_court: 'Amygdalite chronique',
    categorie: 'Gorge',
    frequence: 65,
  },
  {
    code: 'J35.1',
    libelle: 'Hypertrophie des amygdales',
    libelle_court: 'Hypertrophie amygdales',
    categorie: 'Gorge',
    frequence: 70,
  },
  {
    code: 'J35.2',
    libelle: 'Hypertrophie des végétations adénoïdes',
    libelle_court: 'Hypertrophie végétations',
    categorie: 'Gorge',
    frequence: 65,
  },
  {
    code: 'J35.3',
    libelle: 'Hypertrophie des amygdales avec hypertrophie des végétations',
    libelle_court: 'Hypertrophie amygdales+végét.',
    categorie: 'Gorge',
    frequence: 55,
  },
  {
    code: 'J35.8',
    libelle: 'Autres maladies chroniques des amygdales et des végétations',
    libelle_court: 'Maladie amygdales autre',
    categorie: 'Gorge',
    frequence: 30,
  },
  {
    code: 'J35.9',
    libelle: 'Maladie chronique des amygdales et des végétations, sans précision',
    libelle_court: 'Maladie amygdales SAI',
    categorie: 'Gorge',
    frequence: 45,
  },
  {
    code: 'J36',
    libelle: 'Abcès périamygdalien',
    libelle_court: 'Phlegmon amygdalien',
    categorie: 'Gorge',
    frequence: 40,
  },

  // Larynx
  {
    code: 'J37.0',
    libelle: 'Laryngite chronique',
    libelle_court: 'Laryngite chronique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J37.1',
    libelle: 'Laryngo-trachéite chronique',
    libelle_court: 'Laryngo-trachéite chron.',
    categorie: 'Gorge',
    frequence: 30,
  },
  {
    code: 'J38.0',
    libelle: 'Paralysie des cordes vocales et du larynx',
    libelle_court: 'Paralysie corde vocale',
    categorie: 'Gorge',
    frequence: 45,
  },
  {
    code: 'J38.1',
    libelle: 'Polype des cordes vocales et du larynx',
    libelle_court: 'Polype corde vocale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.2',
    libelle: 'Nodules des cordes vocales',
    libelle_court: 'Nodules cordes vocales',
    categorie: 'Gorge',
    frequence: 55,
  },
  {
    code: 'J38.3',
    libelle: 'Autres maladies des cordes vocales',
    libelle_court: 'Maladie corde vocale autre',
    categorie: 'Gorge',
    frequence: 35,
  },
  {
    code: 'J38.4',
    libelle: 'Œdème du larynx',
    libelle_court: 'Œdème larynx',
    categorie: 'Gorge',
    frequence: 30,
  },
  {
    code: 'J38.5',
    libelle: 'Spasme laryngé',
    libelle_court: 'Laryngospasme',
    categorie: 'Gorge',
    frequence: 25,
  },
  {
    code: 'J38.6',
    libelle: 'Sténose du larynx',
    libelle_court: 'Sténose larynx',
    categorie: 'Gorge',
    frequence: 20,
  },
  {
    code: 'J38.7',
    libelle: 'Autres maladies du larynx',
    libelle_court: 'Maladie larynx autre',
    categorie: 'Gorge',
    frequence: 30,
  },

  // Dysphonie
  {
    code: 'R49.0',
    libelle: 'Dysphonie',
    libelle_court: 'Dysphonie',
    categorie: 'Gorge',
    frequence: 75,
  },
  {
    code: 'R49.1',
    libelle: 'Aphonie',
    libelle_court: 'Aphonie',
    categorie: 'Gorge',
    frequence: 35,
  },
  {
    code: 'R49.2',
    libelle: 'Rhinolalie et nasonnement',
    libelle_court: 'Rhinolalie',
    categorie: 'Gorge',
    frequence: 20,
  },

  // ============================================================================
  // COU ET CERVICO-FACIAL
  // ============================================================================

  // Glandes salivaires
  {
    code: 'K11.0',
    libelle: 'Atrophie de glande salivaire',
    libelle_court: 'Atrophie glande saliv.',
    categorie: 'Cou',
    frequence: 15,
  },
  {
    code: 'K11.1',
    libelle: 'Hypertrophie de glande salivaire',
    libelle_court: 'Hypertrophie glande saliv.',
    categorie: 'Cou',
    frequence: 20,
  },
  {
    code: 'K11.2',
    libelle: 'Sialadénite',
    libelle_court: 'Sialadénite',
    categorie: 'Cou',
    frequence: 40,
  },
  {
    code: 'K11.3',
    libelle: 'Abcès de glande salivaire',
    libelle_court: 'Abcès glande saliv.',
    categorie: 'Cou',
    frequence: 25,
  },
  {
    code: 'K11.5',
    libelle: 'Sialolithiase',
    libelle_court: 'Lithiase salivaire',
    categorie: 'Cou',
    frequence: 45,
  },
  {
    code: 'K11.6',
    libelle: 'Mucocèle de glande salivaire',
    libelle_court: 'Mucocèle salivaire',
    categorie: 'Cou',
    frequence: 30,
  },
  {
    code: 'K11.7',
    libelle: 'Troubles de la sécrétion salivaire',
    libelle_court: 'Trouble sécrétion saliv.',
    categorie: 'Cou',
    frequence: 35,
  },

  // Adénopathies et masses cervicales
  {
    code: 'R59.0',
    libelle: 'Adénopathie localisée',
    libelle_court: 'Adénopathie localisée',
    categorie: 'Cou',
    frequence: 65,
  },
  {
    code: 'R59.1',
    libelle: 'Adénopathie généralisée',
    libelle_court: 'Adénopathie généralisée',
    categorie: 'Cou',
    frequence: 30,
  },
  {
    code: 'R59.9',
    libelle: 'Adénopathie, sans précision',
    libelle_court: 'Adénopathie SAI',
    categorie: 'Cou',
    frequence: 55,
  },
  {
    code: 'R22.1',
    libelle: 'Tuméfaction localisée au cou',
    libelle_court: 'Masse cervicale',
    categorie: 'Cou',
    frequence: 50,
  },

  // Thyroïde (fréquent en ORL)
  {
    code: 'E04.0',
    libelle: 'Goitre non toxique diffus',
    libelle_court: 'Goitre diffus',
    categorie: 'Cou',
    frequence: 40,
  },
  {
    code: 'E04.1',
    libelle: 'Nodule thyroïdien non toxique unique',
    libelle_court: 'Nodule thyroïdien unique',
    categorie: 'Cou',
    frequence: 55,
  },
  {
    code: 'E04.2',
    libelle: 'Goitre multinodulaire non toxique',
    libelle_court: 'Goitre multinodulaire',
    categorie: 'Cou',
    frequence: 45,
  },
  {
    code: 'E04.9',
    libelle: 'Goitre non toxique, sans précision',
    libelle_court: 'Goitre SAI',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'E06.0',
    libelle: 'Thyroïdite aiguë',
    libelle_court: 'Thyroïdite aiguë',
    categorie: 'Cou',
    frequence: 20,
  },
  {
    code: 'E06.1',
    libelle: 'Thyroïdite subaiguë',
    libelle_court: 'Thyroïdite subaiguë',
    categorie: 'Cou',
    frequence: 25,
  },
  {
    code: 'E06.3',
    libelle: 'Thyroïdite auto-immune',
    libelle_court: 'Thyroïdite Hashimoto',
    categorie: 'Cou',
    frequence: 35,
  },

  // Kystes congénitaux
  {
    code: 'Q18.0',
    libelle: 'Fistule du sinus, de la fossette et du kyste branchial',
    libelle_court: 'Kyste branchial',
    categorie: 'Cou',
    frequence: 30,
  },
  {
    code: 'Q89.2',
    libelle: 'Kyste du tractus thyréoglosse',
    libelle_court: 'Kyste thyréoglosse',
    categorie: 'Cou',
    frequence: 35,
  },

  // ============================================================================
  // GÉNÉRAL ET SYMPTÔMES
  // ============================================================================

  { code: 'R05', libelle: 'Toux', libelle_court: 'Toux', categorie: 'Général', frequence: 80 },
  {
    code: 'R06.0',
    libelle: 'Dyspnée',
    libelle_court: 'Dyspnée',
    categorie: 'Général',
    frequence: 45,
  },
  {
    code: 'R06.1',
    libelle: 'Stridor',
    libelle_court: 'Stridor',
    categorie: 'Général',
    frequence: 25,
  },
  {
    code: 'R06.5',
    libelle: 'Respiration buccale',
    libelle_court: 'Respiration buccale',
    categorie: 'Général',
    frequence: 55,
  },
  {
    code: 'R06.7',
    libelle: 'Éternuement',
    libelle_court: 'Éternuement',
    categorie: 'Général',
    frequence: 30,
  },
  {
    code: 'R07.0',
    libelle: 'Douleur pharyngée',
    libelle_court: 'Douleur pharynx',
    categorie: 'Général',
    frequence: 70,
  },
  {
    code: 'R09.3',
    libelle: 'Crachats anormaux',
    libelle_court: 'Crachats anormaux',
    categorie: 'Général',
    frequence: 35,
  },
  {
    code: 'R13',
    libelle: 'Dysphagie',
    libelle_court: 'Dysphagie',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'R21',
    libelle: 'Rash et autres éruptions cutanées non spécifiques',
    libelle_court: 'Rash cutané',
    categorie: 'Général',
    frequence: 25,
  },
  {
    code: 'R42',
    libelle: 'Étourdissement et éblouissement',
    libelle_court: 'Étourdissement',
    categorie: 'Général',
    frequence: 55,
  },
  {
    code: 'R43.0',
    libelle: 'Anosmie',
    libelle_court: 'Anosmie',
    categorie: 'Général',
    frequence: 45,
  },
  {
    code: 'R43.1',
    libelle: 'Parosmie',
    libelle_court: 'Parosmie',
    categorie: 'Général',
    frequence: 20,
  },
  {
    code: 'R43.2',
    libelle: 'Paragueusie',
    libelle_court: 'Paragueusie',
    categorie: 'Général',
    frequence: 15,
  },
  {
    code: 'R51',
    libelle: 'Céphalée',
    libelle_court: 'Céphalée',
    categorie: 'Général',
    frequence: 60,
  },
  {
    code: 'R68.2',
    libelle: 'Bouche sèche, sans précision',
    libelle_court: 'Bouche sèche',
    categorie: 'Général',
    frequence: 40,
  },

  // Apnée du sommeil
  {
    code: 'G47.3',
    libelle: 'Apnée du sommeil',
    libelle_court: 'Apnée du sommeil',
    categorie: 'Général',
    frequence: 70,
  },
  {
    code: 'R06.83',
    libelle: 'Ronflement',
    libelle_court: 'Ronflement',
    categorie: 'Général',
    frequence: 65,
  },

  // ============================================================================
  // CODES CIM-10 ADDITIONNELS
  // ============================================================================

  {
    code: 'H60',
    libelle: 'Otite externe',
    libelle_court: 'Otite externe',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.0',
    libelle: 'Abcès de l\'oreille externe',
    libelle_court: 'Abcès de l\'oreille externe',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.1',
    libelle: 'Cellulite phlegmoneuse de l\'oreille externe',
    libelle_court: 'Cellulite phlegmoneuse de l\'oreille e...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.2',
    libelle: 'Otite externe maligne',
    libelle_court: 'Otite externe maligne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.3',
    libelle: 'Autres otites externes infectieuses',
    libelle_court: 'Autres otites externes infectieuses',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.4',
    libelle: 'Cholestéatome de l\'oreille externe',
    libelle_court: 'Cholestéatome de l\'oreille externe',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.5',
    libelle: 'Otite externe aiguë',
    libelle_court: 'Otite externe aiguë',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.8',
    libelle: 'Autres otites externes',
    libelle_court: 'Autres otites externes',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H60.9',
    libelle: 'Otite externe, sans précision',
    libelle_court: 'Otite externe, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H61',
    libelle: 'Autres affections de l\'oreille externe',
    libelle_court: 'Autres affections de l\'oreille externe',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H61.0',
    libelle: 'Périchondrite de l\'oreille externe',
    libelle_court: 'Périchondrite de l\'oreille externe',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H61.1',
    libelle: 'Affections non infectieuses du pavillon de l\'oreille',
    libelle_court: 'Affections non infectieuses du pavill...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H61.8',
    libelle: 'Autres affections précisées de l\'oreille externe',
    libelle_court: 'Autres affections précisées de l\'orei...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H61.9',
    libelle: 'Affection de l\'oreille externe, sans précision',
    libelle_court: 'Affection de l\'oreille externe, sans ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62',
    libelle: 'Affections de l\'oreille externe au cours de maladies classées ailleurs',
    libelle_court: 'Affections de l\'oreille externe au co...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.0',
    libelle: 'Otite externe au cours de maladies bactériennes classées ailleurs',
    libelle_court: 'Otite externe au cours de maladies ba...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.1',
    libelle: 'Otite externe au cours de maladies virales classées ailleurs',
    libelle_court: 'Otite externe au cours de maladies vi...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.2',
    libelle: 'Otite externe au cours de mycoses',
    libelle_court: 'Otite externe au cours de mycoses',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.3',
    libelle: 'Otite externe au cours d\'autres maladies infectieuses et parasitaires classées ailleurs',
    libelle_court: 'Otite externe au cours d\'autres malad...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.4',
    libelle: 'Otite externe au cours d\'autres maladies classées ailleurs',
    libelle_court: 'Otite externe au cours d\'autres malad...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H62.8',
    libelle: 'Autres affections de l\'oreille externe au cours de maladies classées ailleurs',
    libelle_court: 'Autres affections de l\'oreille extern...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65',
    libelle: 'Otite moyenne non suppurée',
    libelle_court: 'Otite moyenne non suppurée',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.0',
    libelle: 'Otite moyenne séreuse aiguë',
    libelle_court: 'Otite moyenne séreuse aiguë',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.1',
    libelle: 'Autres otites moyennes aiguës, non suppurées',
    libelle_court: 'Autres otites moyennes aiguës, non su...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.2',
    libelle: 'Otite moyenne séreuse chronique',
    libelle_court: 'Otite moyenne séreuse chronique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.3',
    libelle: 'Otite moyenne mucoïde chronique',
    libelle_court: 'Otite moyenne mucoïde chronique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.4',
    libelle: 'Autres otites moyennes chroniques, non suppurées',
    libelle_court: 'Autres otites moyennes chroniques, no...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H65.9',
    libelle: 'Otite moyenne non suppurée, sans précision',
    libelle_court: 'Otite moyenne non suppurée, sans préc...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66',
    libelle: 'Otite moyenne suppurée et sans précision',
    libelle_court: 'Otite moyenne suppurée et sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.0',
    libelle: 'Otite moyenne aiguë suppurée',
    libelle_court: 'Otite moyenne aiguë suppurée',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.1',
    libelle: 'Otite moyenne suppurée chronique tubo-tympanique',
    libelle_court: 'Otite moyenne suppurée chronique tubo...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.2',
    libelle: 'Otite moyenne chronique attico-antrale suppurée',
    libelle_court: 'Otite moyenne chronique attico-antral...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.3',
    libelle: 'Autres otites moyennes suppurées chroniques',
    libelle_court: 'Autres otites moyennes suppurées chro...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.4',
    libelle: 'Otite moyenne suppurée, sans précision',
    libelle_court: 'Otite moyenne suppurée, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H66.9',
    libelle: 'Otite moyenne, sans précision',
    libelle_court: 'Otite moyenne, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H67',
    libelle: 'Otite moyenne au cours de maladies classées ailleurs',
    libelle_court: 'Otite moyenne au cours de maladies cl...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H67.0',
    libelle: 'Otite moyenne au cours de maladies bactériennes classées ailleurs',
    libelle_court: 'Otite moyenne au cours de maladies ba...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H67.1',
    libelle: 'Otite moyenne au cours de maladies virales classées ailleurs',
    libelle_court: 'Otite moyenne au cours de maladies vi...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H67.8',
    libelle: 'Otite moyenne au cours d\'autres maladies classées ailleurs',
    libelle_court: 'Otite moyenne au cours d\'autres malad...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H68',
    libelle: 'Salpingite et obstruction de la trompe d\'Eustache',
    libelle_court: 'Salpingite et obstruction de la tromp...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H68.0',
    libelle: 'Salpingite de la trompe d\'Eustache',
    libelle_court: 'Salpingite de la trompe d\'Eustache',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H68.1',
    libelle: 'Obstruction de la trompe d\'Eustache',
    libelle_court: 'Obstruction de la trompe d\'Eustache',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H69',
    libelle: 'Autres affections de la trompe d\'Eustache',
    libelle_court: 'Autres affections de la trompe d\'Eust...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H69.0',
    libelle: 'Distension de la trompe d\'Eustache',
    libelle_court: 'Distension de la trompe d\'Eustache',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H69.8',
    libelle: 'Autres affections précisées de la trompe d\'Eustache',
    libelle_court: 'Autres affections précisées de la tro...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H69.9',
    libelle: 'Affection de la trompe d\'Eustache, sans précision',
    libelle_court: 'Affection de la trompe d\'Eustache, sa...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H70',
    libelle: 'Mastoïdite et affections apparentées',
    libelle_court: 'Mastoïdite et affections apparentées',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H70.0',
    libelle: 'Mastoïdite aiguë',
    libelle_court: 'Mastoïdite aiguë',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H70.1',
    libelle: 'Mastoïdite chronique',
    libelle_court: 'Mastoïdite chronique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H70.8',
    libelle: 'Autres mastoïdites et affections apparentées',
    libelle_court: 'Autres mastoïdites et affections appa...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H70.9',
    libelle: 'Mastoïdite, sans précision',
    libelle_court: 'Mastoïdite, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H71',
    libelle: 'Cholestéatome de l\'oreille moyenne',
    libelle_court: 'Cholestéatome de l\'oreille moyenne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74',
    libelle: 'Autres affections de l\'oreille moyenne et de l\'apophyse mastoïde',
    libelle_court: 'Autres affections de l\'oreille moyenn...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74.1',
    libelle: 'Maladie adhésive de l\'oreille moyenne',
    libelle_court: 'Maladie adhésive de l\'oreille moyenne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74.3',
    libelle: 'Autres anomalies acquises des osselets',
    libelle_court: 'Autres anomalies acquises des osselets',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74.4',
    libelle: 'Polype de l\'oreille moyenne',
    libelle_court: 'Polype de l\'oreille moyenne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74.8',
    libelle: 'Autres affections précisées de l\'oreille moyenne et de l\'apophyse mastoïde',
    libelle_court: 'Autres affections précisées de l\'orei...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H74.9',
    libelle: 'Affection de l\'oreille moyenne et de l\'apophyse mastoïde, sans précision',
    libelle_court: 'Affection de l\'oreille moyenne et de ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H75',
    libelle: 'Autres affections de l\'oreille moyenne et de l\'apophyse mastoïde au cours de maladies classées ailleurs',
    libelle_court: 'Autres affections de l\'oreille moyenn...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H75.0',
    libelle: 'Mastoïdite au cours de maladies infectieuses et parasitaires classées ailleurs',
    libelle_court: 'Mastoïdite au cours de maladies infec...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H75.8',
    libelle: 'Autres affections précisées de l\'oreille moyenne et de l\'apophyse mastoïde au cours de maladies classées ailleurs',
    libelle_court: 'Autres affections précisées de l\'orei...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H80',
    libelle: 'Otospongiose',
    libelle_court: 'Otospongiose',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81',
    libelle: 'Troubles de la fonction vestibulaire',
    libelle_court: 'Troubles de la fonction vestibulaire',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81.0',
    libelle: 'Maladie de Ménière',
    libelle_court: 'Maladie de Ménière',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81.1',
    libelle: 'Vertige bénin paroxystique',
    libelle_court: 'Vertige bénin paroxystique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81.3',
    libelle: 'Autres vertiges périphériques',
    libelle_court: 'Autres vertiges périphériques',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H81.4',
    libelle: 'Vertige d\'origine centrale',
    libelle_court: 'Vertige d\'origine centrale',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H83',
    libelle: 'Autres maladies de l\'oreille interne',
    libelle_court: 'Autres maladies de l\'oreille interne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H83.0',
    libelle: 'Labyrinthite',
    libelle_court: 'Labyrinthite',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H83.3',
    libelle: 'Conséquences du bruit sur l\'oreille interne',
    libelle_court: 'Conséquences du bruit sur l\'oreille i...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H83.8',
    libelle: 'Autres maladies précisées de l\'oreille interne',
    libelle_court: 'Autres maladies précisées de l\'oreill...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H83.9',
    libelle: 'Maladie de l\'oreille interne, sans précision',
    libelle_court: 'Maladie de l\'oreille interne, sans pr...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90',
    libelle: 'Surdité de transmission et neurosensorielle',
    libelle_court: 'Surdité de transmission et neurosenso...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.0',
    libelle: 'Surdité bilatérale de transmission',
    libelle_court: 'Surdité bilatérale de transmission',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.1',
    libelle: 'Surdité unilatérale de transmission sans altération de l\'audition de l\'autre oreille',
    libelle_court: 'Surdité unilatérale de transmission s...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.2',
    libelle: 'Surdité de transmission, sans précision',
    libelle_court: 'Surdité de transmission, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.3',
    libelle: 'Surdité neurosensorielle bilatérale',
    libelle_court: 'Surdité neurosensorielle bilatérale',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.4',
    libelle: 'Surdité neurosensorielle unilatérale sans altération de l\'audition de l\'autre oreille',
    libelle_court: 'Surdité neurosensorielle unilatérale ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.5',
    libelle: 'Surdité neurosensorielle, sans précision',
    libelle_court: 'Surdité neurosensorielle, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.6',
    libelle: 'Surdité bilatérale mixte de transmission et neurosensorielle',
    libelle_court: 'Surdité bilatérale mixte de transmiss...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.7',
    libelle: 'Surdité unilatérale mixte de transmission et neurosensorielle sans altération de l\'audition de l\'autre oreille',
    libelle_court: 'Surdité unilatérale mixte de transmis...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H90.8',
    libelle: 'Surdité mixte de transmission et neurosensorielle, sans précision',
    libelle_court: 'Surdité mixte de transmission et neur...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91',
    libelle: 'Autres pertes de l\'audition',
    libelle_court: 'Autres pertes de l\'audition',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91.0',
    libelle: 'Perte de l\'audition par ototoxicité',
    libelle_court: 'Perte de l\'audition par ototoxicité',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91.2',
    libelle: 'Perte auditive soudaine idiopathique',
    libelle_court: 'Perte auditive soudaine idiopathique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91.3',
    libelle: 'Surdi-mutité, non classée ailleurs',
    libelle_court: 'Surdi-mutité, non classée ailleurs',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91.8',
    libelle: 'Autres pertes précisées de l\'audition',
    libelle_court: 'Autres pertes précisées de l\'audition',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H91.9',
    libelle: 'Perte de l\'audition, sans précision',
    libelle_court: 'Perte de l\'audition, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H92',
    libelle: 'Otalgie et écoulement par l\'oreille',
    libelle_court: 'Otalgie et écoulement par l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H92.0',
    libelle: 'Otalgie',
    libelle_court: 'Otalgie',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H92.1',
    libelle: 'Otorrhée',
    libelle_court: 'Otorrhée',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H92.2',
    libelle: 'Otorragie',
    libelle_court: 'Otorragie',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H93',
    libelle: 'Autres affections de l\'oreille, non classées ailleurs',
    libelle_court: 'Autres affections de l\'oreille, non c...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H93.0',
    libelle: 'Affections vasculaires et dégénératives de l\'oreille',
    libelle_court: 'Affections vasculaires et dégénérativ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H93.1',
    libelle: 'Acouphènes',
    libelle_court: 'Acouphènes',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H93.8',
    libelle: 'Autres affections précisées de l\'oreille',
    libelle_court: 'Autres affections précisées de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H93.9',
    libelle: 'Affection de l\'oreille, sans précision',
    libelle_court: 'Affection de l\'oreille, sans précision',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H94',
    libelle: 'Autres affections de l\'oreille au cours de maladies classées ailleurs',
    libelle_court: 'Autres affections de l\'oreille au cou...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H94.8',
    libelle: 'Autres affections précisées de l\'oreille au cours de maladies classées ailleurs',
    libelle_court: 'Autres affections précisées de l\'orei...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H95',
    libelle: 'Affections de l\'oreille et de l\'apophyse mastoïde après un acte à visée diagnostique et thérapeutique',
    libelle_court: 'Affections de l\'oreille et de l\'apoph...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H95.8',
    libelle: 'Autres affections de l\'oreille et de l\'apophyse mastoïde après un acte à visée diagnostique et thérapeutique',
    libelle_court: 'Autres affections de l\'oreille et de ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'H95.9',
    libelle: 'Affection de l\'oreille et de l\'apophyse mastoïde après un acte à visée diagnostique et thérapeutique, sans précision',
    libelle_court: 'Affection de l\'oreille et de l\'apophy...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'J00',
    libelle: 'Rhinopharyngite [rhume banal]',
    libelle_court: 'Rhinopharyngite [rhume banal]',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01',
    libelle: 'Sinusite aiguë',
    libelle_court: 'Sinusite aiguë',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.0',
    libelle: 'Sinusite maxillaire aiguë',
    libelle_court: 'Sinusite maxillaire aiguë',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.1',
    libelle: 'Sinusite frontale aiguë',
    libelle_court: 'Sinusite frontale aiguë',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.2',
    libelle: 'Sinusite ethmoïdale aiguë',
    libelle_court: 'Sinusite ethmoïdale aiguë',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.3',
    libelle: 'Sinusite sphénoïdale aiguë',
    libelle_court: 'Sinusite sphénoïdale aiguë',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.8',
    libelle: 'Autres sinusites aiguës',
    libelle_court: 'Autres sinusites aiguës',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J01.9',
    libelle: 'Sinusite aiguë, sans précision',
    libelle_court: 'Sinusite aiguë, sans précision',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J02',
    libelle: 'Pharyngite aiguë',
    libelle_court: 'Pharyngite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J02.0',
    libelle: 'Pharyngite à streptocoques',
    libelle_court: 'Pharyngite à streptocoques',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J02.8',
    libelle: 'Pharyngite aiguë due à d\'autres micro-organismes précisés',
    libelle_court: 'Pharyngite aiguë due à d\'autres micro...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J02.9',
    libelle: 'Pharyngite, sans précision',
    libelle_court: 'Pharyngite, sans précision',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J03',
    libelle: 'Amygdalite aiguë',
    libelle_court: 'Amygdalite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J03.0',
    libelle: 'Amygdalite à streptocoques',
    libelle_court: 'Amygdalite à streptocoques',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J03.8',
    libelle: 'Amygdalite aiguë à d\'autres micro-organismes précisés',
    libelle_court: 'Amygdalite aiguë à d\'autres micro-org...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J03.9',
    libelle: 'Amygdalite, sans précision',
    libelle_court: 'Amygdalite, sans précision',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J04',
    libelle: 'Laryngite et trachéite aiguës',
    libelle_court: 'Laryngite et trachéite aiguës',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J04.0',
    libelle: 'Laryngite aiguë',
    libelle_court: 'Laryngite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J04.1',
    libelle: 'Trachéite aiguë',
    libelle_court: 'Trachéite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J04.2',
    libelle: 'Laryngo-trachéite aiguë',
    libelle_court: 'Laryngo-trachéite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J05',
    libelle: 'Laryngite obstructive aiguë [croup] et épiglottite aiguë',
    libelle_court: 'Laryngite obstructive aiguë [croup] e...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J05.0',
    libelle: 'Laryngite obstructive [croup]',
    libelle_court: 'Laryngite obstructive [croup]',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J05.1',
    libelle: 'Épiglottite aiguë',
    libelle_court: 'Épiglottite aiguë',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J06',
    libelle: 'Infections aiguës des voies respiratoires supérieures, à localisations multiples et non précisées',
    libelle_court: 'Infections aiguës des voies respirato...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J30',
    libelle: 'Rhinite allergique et vasomotrice',
    libelle_court: 'Rhinite allergique et vasomotrice',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.0',
    libelle: 'Rhinite vasomotrice',
    libelle_court: 'Rhinite vasomotrice',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.1',
    libelle: 'Rhinite allergique due au pollen',
    libelle_court: 'Rhinite allergique due au pollen',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.2',
    libelle: 'Autres rhinites allergiques saisonnières',
    libelle_court: 'Autres rhinites allergiques saisonnières',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.3',
    libelle: 'Autres rhinites allergiques',
    libelle_court: 'Autres rhinites allergiques',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J30.4',
    libelle: 'Rhinite allergique, sans précision',
    libelle_court: 'Rhinite allergique, sans précision',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J31',
    libelle: 'Rhinite, rhinopharyngite et pharyngite chroniques',
    libelle_court: 'Rhinite, rhinopharyngite et pharyngit...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'J31.0',
    libelle: 'Rhinite chronique',
    libelle_court: 'Rhinite chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J31.1',
    libelle: 'Rhinopharyngite chronique',
    libelle_court: 'Rhinopharyngite chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J31.2',
    libelle: 'Pharyngite chronique',
    libelle_court: 'Pharyngite chronique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J32',
    libelle: 'Sinusite chronique',
    libelle_court: 'Sinusite chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.0',
    libelle: 'Sinusite maxillaire chronique',
    libelle_court: 'Sinusite maxillaire chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.1',
    libelle: 'Sinusite frontale chronique',
    libelle_court: 'Sinusite frontale chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.2',
    libelle: 'Sinusite ethmoïdale chronique',
    libelle_court: 'Sinusite ethmoïdale chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.3',
    libelle: 'Sinusite sphénoïdale chronique',
    libelle_court: 'Sinusite sphénoïdale chronique',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.8',
    libelle: 'Autres sinusites chroniques',
    libelle_court: 'Autres sinusites chroniques',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J32.9',
    libelle: 'Sinusite chronique, sans précision',
    libelle_court: 'Sinusite chronique, sans précision',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J33',
    libelle: 'Polype nasal',
    libelle_court: 'Polype nasal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J33.0',
    libelle: 'Polype de la cavité nasale',
    libelle_court: 'Polype de la cavité nasale',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J33.1',
    libelle: 'Polype du sinus ethmoïdal',
    libelle_court: 'Polype du sinus ethmoïdal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J33.8',
    libelle: 'Autres polypes des sinus',
    libelle_court: 'Autres polypes des sinus',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J33.9',
    libelle: 'Polype nasal, sans précision',
    libelle_court: 'Polype nasal, sans précision',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34',
    libelle: 'Autres maladies du nez et des sinus du nez',
    libelle_court: 'Autres maladies du nez et des sinus d...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34.0',
    libelle: 'Abcès, furoncle et anthrax du nez',
    libelle_court: 'Abcès, furoncle et anthrax du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34.1',
    libelle: 'Kyste et mucocèle du nez et des sinus du nez',
    libelle_court: 'Kyste et mucocèle du nez et des sinus...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34.2',
    libelle: 'Déviation de la cloison nasale',
    libelle_court: 'Déviation de la cloison nasale',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34.3',
    libelle: 'Hypertrophie des cornets du nez',
    libelle_court: 'Hypertrophie des cornets du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J34.8',
    libelle: 'Autres maladies précisées du nez et des sinus du nez',
    libelle_court: 'Autres maladies précisées du nez et d...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'J35',
    libelle: 'Maladies chroniques des amygdales et des végétations adénoïdes',
    libelle_court: 'Maladies chroniques des amygdales et ...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.0',
    libelle: 'Amygdalite chronique',
    libelle_court: 'Amygdalite chronique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.1',
    libelle: 'Hypertrophie des amygdales',
    libelle_court: 'Hypertrophie des amygdales',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.2',
    libelle: 'Hypertrophie des végétations adénoïdes',
    libelle_court: 'Hypertrophie des végétations adénoïdes',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.3',
    libelle: 'Hypertrophie des amygdales et des végétations adénoïdes',
    libelle_court: 'Hypertrophie des amygdales et des vég...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.8',
    libelle: 'Autres maladies chroniques des amygdales et des végétations adénoïdes',
    libelle_court: 'Autres maladies chroniques des amygda...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J35.9',
    libelle: 'Maladie des amygdales et des végétations adénoïdes, sans précision',
    libelle_court: 'Maladie des amygdales et des végétati...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J36',
    libelle: 'Angine phlegmoneuse',
    libelle_court: 'Angine phlegmoneuse',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J37',
    libelle: 'Laryngite et laryngo-trachéite chroniques',
    libelle_court: 'Laryngite et laryngo-trachéite chroni...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J37.0',
    libelle: 'Laryngite chronique',
    libelle_court: 'Laryngite chronique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J37.1',
    libelle: 'Laryngo-trachéite chronique',
    libelle_court: 'Laryngo-trachéite chronique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38',
    libelle: 'Maladies des cordes vocales et du larynx, non classées ailleurs',
    libelle_court: 'Maladies des cordes vocales et du lar...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.0',
    libelle: 'Paralysie des cordes vocales et du larynx',
    libelle_court: 'Paralysie des cordes vocales et du la...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.1',
    libelle: 'Polype des cordes vocales et du larynx',
    libelle_court: 'Polype des cordes vocales et du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.2',
    libelle: 'Nodules des cordes vocales',
    libelle_court: 'Nodules des cordes vocales',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.3',
    libelle: 'Autres maladies des cordes vocales',
    libelle_court: 'Autres maladies des cordes vocales',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.4',
    libelle: 'Oedème du larynx',
    libelle_court: 'Oedème du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.5',
    libelle: 'Spasme laryngé',
    libelle_court: 'Spasme laryngé',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.6',
    libelle: 'Sténose du larynx',
    libelle_court: 'Sténose du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J38.7',
    libelle: 'Autres maladies du larynx',
    libelle_court: 'Autres maladies du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J39',
    libelle: 'Autres maladies des voies respiratoires supérieures',
    libelle_court: 'Autres maladies des voies respiratoir...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J39.1',
    libelle: 'Autres abcès du pharynx',
    libelle_court: 'Autres abcès du pharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J39.2',
    libelle: 'Autres maladies du pharynx',
    libelle_court: 'Autres maladies du pharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'J39.8',
    libelle: 'Autres maladies des voies respiratoires supérieures précisées',
    libelle_court: 'Autres maladies des voies respiratoir...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'K11',
    libelle: 'Maladies des glandes salivaires',
    libelle_court: 'Maladies des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.0',
    libelle: 'Atrophie des glandes salivaires',
    libelle_court: 'Atrophie des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.1',
    libelle: 'Hypertrophie des glandes salivaires',
    libelle_court: 'Hypertrophie des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.2',
    libelle: 'Sialoadénite',
    libelle_court: 'Sialoadénite',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.3',
    libelle: 'Abcès des glandes salivaires',
    libelle_court: 'Abcès des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.4',
    libelle: 'Fistule des glandes salivaires',
    libelle_court: 'Fistule des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.5',
    libelle: 'Sialolithiase',
    libelle_court: 'Sialolithiase',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.6',
    libelle: 'Mucocèle des glandes salivaires',
    libelle_court: 'Mucocèle des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.7',
    libelle: 'Troubles de la sécrétion salivaire',
    libelle_court: 'Troubles de la sécrétion salivaire',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.8',
    libelle: 'Autres maladies des glandes salivaires',
    libelle_court: 'Autres maladies des glandes salivaires',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'K11.9',
    libelle: 'Maladie des glandes salivaires, sans précision',
    libelle_court: 'Maladie des glandes salivaires, sans ...',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'Q16',
    libelle: 'Malformations congénitales de l\'oreille avec atteinte de l\'audition',
    libelle_court: 'Malformations congénitales de l\'oreil...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q16.0',
    libelle: 'Absence congénitale du pavillon de l\'oreille',
    libelle_court: 'Absence congénitale du pavillon de l\'...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q16.2',
    libelle: 'Absence de trompe d\'Eustache',
    libelle_court: 'Absence de trompe d\'Eustache',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q16.4',
    libelle: 'Autres malformations congénitales de l\'oreille moyenne',
    libelle_court: 'Autres malformations congénitales de ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q16.5',
    libelle: 'Malformation congénitale de l\'oreille interne',
    libelle_court: 'Malformation congénitale de l\'oreille...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q16.9',
    libelle: 'Malformation congénitale de l\'oreille, sans précision',
    libelle_court: 'Malformation congénitale de l\'oreille...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17',
    libelle: 'Autres malformations congénitales de l\'oreille',
    libelle_court: 'Autres malformations congénitales de ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17.3',
    libelle: 'Autres déformations de l\'oreille',
    libelle_court: 'Autres déformations de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17.4',
    libelle: 'Anomalie de position de l\'oreille',
    libelle_court: 'Anomalie de position de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17.5',
    libelle: 'Oreilles proéminentes',
    libelle_court: 'Oreilles proéminentes',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17.8',
    libelle: 'Autres malformations congénitales précisées de l\'oreille',
    libelle_court: 'Autres malformations congénitales pré...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q17.9',
    libelle: 'Malformation congénitale de l\'oreille, sans précision',
    libelle_court: 'Malformation congénitale de l\'oreille...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Q30',
    libelle: 'Malformations congénitales du nez',
    libelle_court: 'Malformations congénitales du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'Q30.1',
    libelle: 'Agénésie et hypoplasie du nez',
    libelle_court: 'Agénésie et hypoplasie du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'Q30.8',
    libelle: 'Autres malformations congénitales du nez',
    libelle_court: 'Autres malformations congénitales du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'Q30.9',
    libelle: 'Malformation congénitale du nez, sans précision',
    libelle_court: 'Malformation congénitale du nez, sans...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'Q31',
    libelle: 'Malformations congénitales du larynx',
    libelle_court: 'Malformations congénitales du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.0',
    libelle: 'Ptérygion du larynx',
    libelle_court: 'Ptérygion du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.1',
    libelle: 'Sténose sous-glottique congénitale',
    libelle_court: 'Sténose sous-glottique congénitale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.2',
    libelle: 'Hypoplasie du larynx',
    libelle_court: 'Hypoplasie du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.3',
    libelle: 'Laryngocèle',
    libelle_court: 'Laryngocèle',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.5',
    libelle: 'Laryngomalacie congénitale',
    libelle_court: 'Laryngomalacie congénitale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.8',
    libelle: 'Autres malformations congénitales du larynx',
    libelle_court: 'Autres malformations congénitales du ...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q31.9',
    libelle: 'Malformation congénitale du larynx, sans précision',
    libelle_court: 'Malformation congénitale du larynx, s...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q38.4',
    libelle: 'Malformations congénitales des glandes et des conduits salivaires',
    libelle_court: 'Malformations congénitales des glande...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q38.7',
    libelle: 'Poche pharyngée',
    libelle_court: 'Poche pharyngée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'Q38.8',
    libelle: 'Autres malformations congénitales du pharynx',
    libelle_court: 'Autres malformations congénitales du ...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C07',
    libelle: 'Tumeur maligne de la glande parotide',
    libelle_court: 'Tumeur maligne de la glande parotide',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C08',
    libelle: 'Tumeur maligne des glandes salivaires principales, autres et non précisées',
    libelle_court: 'Tumeur maligne des glandes salivaires...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C08.0',
    libelle: 'Tumeur maligne de la glande sous-maxillaire',
    libelle_court: 'Tumeur maligne de la glande sous-maxi...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C08.1',
    libelle: 'Tumeur maligne de la glande sublinguale',
    libelle_court: 'Tumeur maligne de la glande sublinguale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C08.8',
    libelle: 'Tumeur maligne à localisations contiguës des glandes salivaires principales',
    libelle_court: 'Tumeur maligne à localisations contig...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C08.9',
    libelle: 'Tumeur maligne de la glande salivaire, sans précision',
    libelle_court: 'Tumeur maligne de la glande salivaire...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C09',
    libelle: 'Tumeur maligne de l\'amygdale',
    libelle_court: 'Tumeur maligne de l\'amygdale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C09.1',
    libelle: 'Tumeur maligne du pilier de l\'amygdale',
    libelle_court: 'Tumeur maligne du pilier de l\'amygdale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C09.8',
    libelle: 'Tumeur maligne à localisations contiguës de l\'amygdale',
    libelle_court: 'Tumeur maligne à localisations contig...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C09.9',
    libelle: 'Tumeur maligne de l\'amygdale, sans précision',
    libelle_court: 'Tumeur maligne de l\'amygdale, sans pr...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C10',
    libelle: 'Tumeur maligne de l\'oropharynx',
    libelle_court: 'Tumeur maligne de l\'oropharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C10.2',
    libelle: 'Tumeur maligne de la paroi latérale de l\'oropharynx',
    libelle_court: 'Tumeur maligne de la paroi latérale d...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C11',
    libelle: 'Tumeur maligne du rhinopharynx',
    libelle_court: 'Tumeur maligne du rhinopharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C11.9',
    libelle: 'Tumeur maligne du rhinopharynx, sans précision',
    libelle_court: 'Tumeur maligne du rhinopharynx, sans ...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C12',
    libelle: 'Tumeur maligne du sinus piriforme',
    libelle_court: 'Tumeur maligne du sinus piriforme',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C13',
    libelle: 'Tumeur maligne de l\'hypopharynx',
    libelle_court: 'Tumeur maligne de l\'hypopharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C13.9',
    libelle: 'Tumeur maligne de l\'hypopharynx, sans précision',
    libelle_court: 'Tumeur maligne de l\'hypopharynx, sans...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C14',
    libelle: 'Tumeur maligne de la lèvre, de la cavité buccale et du pharynx, de sièges autres et mal définis',
    libelle_court: 'Tumeur maligne de la lèvre, de la cav...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C14.0',
    libelle: 'Tumeur maligne du pharynx, sans précision',
    libelle_court: 'Tumeur maligne du pharynx, sans préci...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C14.8',
    libelle: 'Tumeur maligne à localisations contiguës de la lèvre, de la cavité buccale et du pharynx',
    libelle_court: 'Tumeur maligne à localisations contig...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C30',
    libelle: 'Tumeur maligne des fosses nasales et de l\'oreille moyenne',
    libelle_court: 'Tumeur maligne des fosses nasales et ...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'C30.0',
    libelle: 'Tumeur maligne des fosses nasales',
    libelle_court: 'Tumeur maligne des fosses nasales',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C30.1',
    libelle: 'Tumeur maligne de l\'oreille moyenne',
    libelle_court: 'Tumeur maligne de l\'oreille moyenne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'C31',
    libelle: 'Tumeur maligne des sinus de la face',
    libelle_court: 'Tumeur maligne des sinus de la face',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.0',
    libelle: 'Tumeur maligne du sinus maxillaire',
    libelle_court: 'Tumeur maligne du sinus maxillaire',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.1',
    libelle: 'Tumeur maligne du sinus ethmoïdal',
    libelle_court: 'Tumeur maligne du sinus ethmoïdal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.2',
    libelle: 'Tumeur maligne du sinus frontal',
    libelle_court: 'Tumeur maligne du sinus frontal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.3',
    libelle: 'Tumeur maligne du sinus sphénoïdal',
    libelle_court: 'Tumeur maligne du sinus sphénoïdal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.8',
    libelle: 'Tumeur maligne à localisations contiguës des sinus de la face',
    libelle_court: 'Tumeur maligne à localisations contig...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C31.9',
    libelle: 'Tumeur maligne des sinus de la face, sans précision',
    libelle_court: 'Tumeur maligne des sinus de la face, ...',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'C32',
    libelle: 'Tumeur maligne du larynx',
    libelle_court: 'Tumeur maligne du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.0',
    libelle: 'Tumeur maligne de la glotte',
    libelle_court: 'Tumeur maligne de la glotte',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.1',
    libelle: 'Tumeur maligne de l\'étage sus-glottique',
    libelle_court: 'Tumeur maligne de l\'étage sus-glottique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.2',
    libelle: 'Tumeur maligne de l\'étage sous-glottique',
    libelle_court: 'Tumeur maligne de l\'étage sous-glottique',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.3',
    libelle: 'Tumeur maligne du cartilage laryngé',
    libelle_court: 'Tumeur maligne du cartilage laryngé',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.8',
    libelle: 'Tumeur maligne à localisations contiguës du larynx',
    libelle_court: 'Tumeur maligne à localisations contig...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C32.9',
    libelle: 'Tumeur maligne du larynx, sans précision',
    libelle_court: 'Tumeur maligne du larynx, sans précision',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'C43.2',
    libelle: 'Mélanome malin de l\'oreille et du conduit auditif externe',
    libelle_court: 'Mélanome malin de l\'oreille et du con...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'C44.2',
    libelle: 'Tumeur maligne de la peau de l\'oreille et du conduit auditif externe',
    libelle_court: 'Tumeur maligne de la peau de l\'oreill...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D10',
    libelle: 'Tumeur bénigne de la bouche et du larynx',
    libelle_court: 'Tumeur bénigne de la bouche et du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D10.4',
    libelle: 'Tumeur bénigne d\'une amygdale',
    libelle_court: 'Tumeur bénigne d\'une amygdale',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D10.9',
    libelle: 'Tumeur bénigne du pharynx, sans précision',
    libelle_court: 'Tumeur bénigne du pharynx, sans préci...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D11',
    libelle: 'Tumeur bénigne des glandes salivaires principales',
    libelle_court: 'Tumeur bénigne des glandes salivaires...',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'D11.0',
    libelle: 'Tumeur bénigne de la glande parotide',
    libelle_court: 'Tumeur bénigne de la glande parotide',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'D11.7',
    libelle: 'Tumeur bénigne d\'autres glandes salivaires principales',
    libelle_court: 'Tumeur bénigne d\'autres glandes saliv...',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'D11.9',
    libelle: 'Tumeur bénigne de la glande salivaire, sans précision',
    libelle_court: 'Tumeur bénigne de la glande salivaire...',
    categorie: 'Cou',
    frequence: 50,
  },
  {
    code: 'D14',
    libelle: 'Tumeur bénigne de l\'oreille moyenne et de l\'appareil respiratoire',
    libelle_court: 'Tumeur bénigne de l\'oreille moyenne e...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D14.0',
    libelle: 'Tumeur bénigne de l\'oreille moyenne, des fosses nasales et du sinus de la face',
    libelle_court: 'Tumeur bénigne de l\'oreille moyenne, ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D14.1',
    libelle: 'Tumeur bénigne du larynx',
    libelle_court: 'Tumeur bénigne du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D02.0',
    libelle: 'Carcinome in situ du larynx',
    libelle_court: 'Carcinome in situ du larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D03.2',
    libelle: 'Mélanome in situ de l\'oreille et du conduit auditif externe',
    libelle_court: 'Mélanome in situ de l\'oreille et du c...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D04.2',
    libelle: 'Carcinome in situ de la peau de l\'oreille et du conduit auditif externe',
    libelle_court: 'Carcinome in situ de la peau de l\'ore...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D22.2',
    libelle: 'Naevus à mélanocytes de l\'oreille et du conduit auditif externe',
    libelle_court: 'Naevus à mélanocytes de l\'oreille et ...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D23.2',
    libelle: 'Tumeur bénigne de la peau de l\'oreille et du conduit auditif externe',
    libelle_court: 'Tumeur bénigne de la peau de l\'oreill...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'D37.0',
    libelle: 'Tumeur à évolution imprévisible ou inconnue de la lèvre, de la cavité buccale et du pharynx',
    libelle_court: 'Tumeur à évolution imprévisible ou in...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'D38.0',
    libelle: 'Tumeur à évolution imprévisible ou inconnue du larynx',
    libelle_court: 'Tumeur à évolution imprévisible ou in...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'R04.0',
    libelle: 'Épistaxis',
    libelle_court: 'Épistaxis',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'R13',
    libelle: 'Dysphagie',
    libelle_court: 'Dysphagie',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'R42',
    libelle: 'Étourdissements et éblouissements',
    libelle_court: 'Étourdissements et éblouissements',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'R49.0',
    libelle: 'Dysphonie',
    libelle_court: 'Dysphonie',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'R49.1',
    libelle: 'Aphonie',
    libelle_court: 'Aphonie',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'S00.4',
    libelle: 'Lésion traumatique superficielle de l\'oreille',
    libelle_court: 'Lésion traumatique superficielle de l...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'S00.3',
    libelle: 'Lésion traumatique superficielle du nez',
    libelle_court: 'Lésion traumatique superficielle du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S01.2',
    libelle: 'Plaie ouverte du nez',
    libelle_court: 'Plaie ouverte du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S01.3',
    libelle: 'Plaie ouverte de l\'oreille',
    libelle_court: 'Plaie ouverte de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'S02.2',
    libelle: 'Fracture des os du nez',
    libelle_court: 'Fracture des os du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S02.20',
    libelle: 'Fracture fermée des os du nez',
    libelle_court: 'Fracture fermée des os du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S02.21',
    libelle: 'Fracture ouverte des os du nez',
    libelle_court: 'Fracture ouverte des os du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S03.1',
    libelle: 'Luxation de la cloison du nez',
    libelle_court: 'Luxation de la cloison du nez',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'S08.1',
    libelle: 'Amputation traumatique de l\'oreille',
    libelle_court: 'Amputation traumatique de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'S11.0',
    libelle: 'Plaie ouverte avec atteinte du larynx et de la trachée',
    libelle_court: 'Plaie ouverte avec atteinte du larynx...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'S11.2',
    libelle: 'Plaie ouverte avec atteinte du pharynx et de l\'oesophage cervical',
    libelle_court: 'Plaie ouverte avec atteinte du pharyn...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'S17.0',
    libelle: 'Écrasement du larynx et de la trachée',
    libelle_court: 'Écrasement du larynx et de la trachée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T16',
    libelle: 'Corps étranger dans l\'oreille',
    libelle_court: 'Corps étranger dans l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'T17.0',
    libelle: 'Corps étranger dans un sinus nasal',
    libelle_court: 'Corps étranger dans un sinus nasal',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'T17.1',
    libelle: 'Corps étranger dans une narine',
    libelle_court: 'Corps étranger dans une narine',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'T17.2',
    libelle: 'Corps étranger dans le pharynx',
    libelle_court: 'Corps étranger dans le pharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T17.3',
    libelle: 'Corps étranger dans le larynx',
    libelle_court: 'Corps étranger dans le larynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T70.0',
    libelle: 'Barotraumatisme de l\'oreille',
    libelle_court: 'Barotraumatisme de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'T70.1',
    libelle: 'Barotraumatisme des sinus',
    libelle_court: 'Barotraumatisme des sinus',
    categorie: 'Nez',
    frequence: 50,
  },
  {
    code: 'T27.0',
    libelle: 'Brûlure du larynx et de la trachée',
    libelle_court: 'Brûlure du larynx et de la trachée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T27.4',
    libelle: 'Corrosion du larynx et de la trachée',
    libelle_court: 'Corrosion du larynx et de la trachée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T28.0',
    libelle: 'Brûlure de la bouche et du pharynx',
    libelle_court: 'Brûlure de la bouche et du pharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'T28.5',
    libelle: 'Corrosion de la bouche et du pharynx',
    libelle_court: 'Corrosion de la bouche et du pharynx',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'A18.6',
    libelle: 'Tuberculose de l\'oreille',
    libelle_court: 'Tuberculose de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'A36.0',
    libelle: 'Diphtérie pharyngée',
    libelle_court: 'Diphtérie pharyngée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'A36.2',
    libelle: 'Diphtérie laryngée',
    libelle_court: 'Diphtérie laryngée',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'A38',
    libelle: 'Scarlatine',
    libelle_court: 'Scarlatine',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'A69.1',
    libelle: 'Autres infections dites de Vincent',
    libelle_court: 'Autres infections dites de Vincent',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'A88.1',
    libelle: 'Vertige épidémique',
    libelle_court: 'Vertige épidémique',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'B05.3',
    libelle: 'Rougeole compliquée d\'une otite moyenne',
    libelle_court: 'Rougeole compliquée d\'une otite moyenne',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'B08.5',
    libelle: 'Pharyngite vésiculaire due à un entérovirus',
    libelle_court: 'Pharyngite vésiculaire due à un entér...',
    categorie: 'Gorge',
    frequence: 50,
  },
  {
    code: 'B27.9',
    libelle: 'Mononucléose infectieuse, sans précision',
    libelle_court: 'Mononucléose infectieuse, sans précision',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'B44.8',
    libelle: 'Autres formes d\'aspergillose',
    libelle_court: 'Autres formes d\'aspergillose',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z01.1',
    libelle: 'Examen des oreilles et de l\'audition',
    libelle_court: 'Examen des oreilles et de l\'audition',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Z13.51',
    libelle: 'Examen spécial de dépistage des affections des oreilles',
    libelle_court: 'Examen spécial de dépistage des affec...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Z13.52',
    libelle: 'Examen spécial de dépistage des affections des yeux et des oreilles',
    libelle_court: 'Examen spécial de dépistage des affec...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Z41.3',
    libelle: 'Perçage du lobe de l\'oreille',
    libelle_court: 'Perçage du lobe de l\'oreille',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Z82.2',
    libelle: 'Antécédents familiaux de surdité et perte d\'audition',
    libelle_court: 'Antécédents familiaux de surdité et p...',
    categorie: 'Oreille',
    frequence: 50,
  },
  {
    code: 'Z80.20',
    libelle: 'Antécédents familiaux de tumeur maligne des voies aériennes supérieures et de l\'oreille moyenne',
    libelle_court: 'Antécédents familiaux de tumeur malig...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z85.20',
    libelle: 'Antécédents personnels de tumeur maligne des voies aériennes supérieures et de l\'oreille moyenne',
    libelle_court: 'Antécédents personnels de tumeur mali...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z85.2',
    libelle: 'Antécédents personnels de tumeur maligne d\'autres organes respiratoires et intrathoraciques',
    libelle_court: 'Antécédents personnels de tumeur mali...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z87.0',
    libelle: 'Antécédents personnels de maladies de l\'appareil respiratoire',
    libelle_court: 'Antécédents personnels de maladies de...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z86.6',
    libelle: 'Antécédents personnels de maladies du système nerveux et des organes des sens',
    libelle_court: 'Antécédents personnels de maladies du...',
    categorie: 'Général',
    frequence: 50,
  },
  {
    code: 'Z96.3',
    libelle: 'Présence d\'un larynx artificiel',
    libelle_court: 'Présence d\'un larynx artificiel',
    categorie: 'Gorge',
    frequence: 50,
  },

// Total new codes: 321
];


export function searchCIM10Codes(query: string, limit = 20, categorie?: string): CIM10Code[] {
  const normalizedQuery = query
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

  let filtered = CIM10_ORL_CODES.filter((code) => {
    const normalizedCode = code.code.toLowerCase();
    const normalizedLibelle = code.libelle
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');
    const normalizedLibelleCourt = code.libelle_court
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '');

    return (
      normalizedCode.includes(normalizedQuery) ||
      normalizedLibelle.includes(normalizedQuery) ||
      normalizedLibelleCourt.includes(normalizedQuery)
    );
  });

  if (categorie) {
    filtered = filtered.filter((code) => code.categorie === categorie);
  }

  filtered.sort((a, b) => (b.frequence ?? 0) - (a.frequence ?? 0));

  return filtered.slice(0, limit);
}

export function getCIM10ByCode(code: string): CIM10Code | undefined {
  return CIM10_ORL_CODES.find((c) => c.code === code);
}

export function getAllCategories(): string[] {
  return [...new Set(CIM10_ORL_CODES.map((c) => c.categorie))];
}
